name: cts

on:
  push:
  pull_request:

jobs:
  telemetry-cts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r telemetry_cts/requirements.txt

      - name: Validate schemas
        run: |
          python telemetry_cts/ct/validate_schema.py

      - name: Verify audit stream
        run: |
          python telemetry_cts/ct/run_chain_verifier.py --profile audit telemetry_cts/fixtures/tel/tel-stream-valid.jsonl

      - name: Verify HA signed stream
        run: |
          python telemetry_cts/ct/run_chain_verifier.py --profile ha telemetry_cts/fixtures/tel/tel-stream-signed-valid.jsonl
